check usermod return.

diff --git a/opencore-tools/change-user-password b/opencore-tools/change-user-password
--- a/opencore-tools/change-user-password
+++ b/opencore-tools/change-user-password
@@ -28,4 +28,8 @@ if [ -z "$PASSWORD" ]; then
   exit 1
 fi
 
-/usr/sbin/usermod -p "$PASSWORD" "$USERNAME"
+/usr/sbin/usermod -p "$PASSWORD" "$USERNAME" || {
+  echo "Usermod failed"
+  exit 1
+}
+
